### ISSUE TITLE
Could not initialize call to CTFPlayer::AddCustomAttribute

### ISSUE THREAD

**Issue by Slips-PC** [nosoop/tf2attributes#7]
Title says all. This error is shown any time i try to run `sm plugins load tf2attributes`.

**Comment by nosoop** [comment]
Hi; thanks for the report.  It sounds the file `gamedata/tf2.attributes.txt` is outdated (perhaps you had FlaminSarge's version previously installed) &mdash; you'll need to install the copy from this project's release and possibly restart your server.

**Comment by Slips-PC** [comment]
Sure enough, that was my issue. Thank you for the punctual response!
